# Lista 03

## Ex 01

In [16]:
for i in range(0,3*3+1,3):
    if i>0:
        print(i)

3
6
9

## Ex 02

In [19]:
for i in range(0,100+1,1):
    if i>0:
        print(i)

print("\n")

var=1

while var<=100:
    print(var)
    var=var+1

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100


1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99
100

## Ex 03

In [20]:
var=10

while var>0:
    print(var)
    var=var-1

print("\nFim! Boooooooom")

10
9
8
7
6
5
4
3
2
1

Fim! Boooooooom

## Ex 04

In [23]:
var=1

while var<=100000:
    print(var)
    var=var+1000
    rest=100000-var
    
    if rest<=1000:
        print(var+rest)

1
1001
2001
3001
4001
5001
6001
7001
8001
9001
10001
11001
12001
13001
14001
15001
16001
17001
18001
19001
20001
21001
22001
23001
24001
25001
26001
27001
28001
29001
30001
31001
32001
33001
34001
35001
36001
37001
38001
39001
40001
41001
42001
43001
44001
45001
46001
47001
48001
49001
50001
51001
52001
53001
54001
55001
56001
57001
58001
59001
60001
61001
62001
63001
64001
65001
66001
67001
68001
69001
70001
71001
72001
73001
74001
75001
76001
77001
78001
79001
80001
81001
82001
83001
84001
85001
86001
87001
88001
89001
90001
91001
92001
93001
94001
95001
96001
97001
98001
100000
99001
100000

## Ex 05

In [27]:
total=0
for i in range(0,10,1):
    n=float(input("\nDigite um valor para ser somado: "))
    total=total+n
    
print(f"\nO total é {total:.2f}")

Digite um valor para ser somado: 10

Digite um valor para ser somado: 20

Digite um valor para ser somado: 30

Digite um valor para ser somado: 40

Digite um valor para ser somado: 50

Digite um valor para ser somado: 60

Digite um valor para ser somado: 70

Digite um valor para ser somado: 80

Digite um valor para ser somado: 90

Digite um valor para ser somado: 100

O total é 550.00

## Ex 06

In [29]:
total=0
for i in range(0,10,1):
    n=float(input("\nDigite um valor para ser somado: "))
    total=total+n

total=total/10
print(f"\nO total é {total:.2f}")

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

Digite um valor para ser somado: 5

O total é 5.00

## Ex 07

In [37]:
i=0
total=0

while i<10:
    var=int(input("\/Digite um número inteiro positivo: "))
    
    if var>=0:
        total=total+var
        i=i+1
        
total=total/10
print(f"A média dos valores é: {total:.2f}")

\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: -3
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
\/Digite um número inteiro positivo: 5
A média dos valores é: 5.00

## Ex 09

In [42]:
rep=int(input("Quantos números naturais impares você deseja? "))
i=0
y=0

while y<rep:
    if i%2==0:
        i=i+1
    else:
        print(i)
        i=i+1
        y=y+1

Quantos números naturais impares você deseja? 25
1
3
5
7
9
11
13
15
17
19
21
23
25
27
29
31
33
35
37
39
41
43
45
47
49

## Ex 10

In [43]:
total=0
i=0
var=0

while var<=50:
    
    if i%2==0:
        total=total+i
        var=var+1
        i=i+1
    else:
        i=i+1

print(f"\nA somatória dos 50 primeiros números é {total}")

A somatória dos 50 primeiros números é 2550